[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 9600
board_upload.speed = 115200

lib_deps =
    arduino-libraries/Servo
    marcoschwartz/LiquidCrystal_I2C